name:                schnorr-cli
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/prolic/schnorr-cli#readme
license:             MIT
author:              Sascha-Oliver Prolic
maintainer:          saschaprolic@googlemail.com
copyright:           2022 Sascha-Oliver Prolic
#category:
extra-source-files:
- README.md

default-extensions:
- OverloadedStrings

dependencies:
  - base >=4.9 && <5
  - base16 >=0.3.0.1
  - bytestring >=0.10.8 && <0.11
  - cryptohash-sha256
  - data-default
  - optparse-applicative
  - optparse-simple
  - secp256k1-schnorr
  - text

executables:
  app:
    source-dirs:      src
    main:             Main.hs
    ghc-options:
    - -fwarn-incomplete-patterns
    - -threaded
